export const trainingValues = [
  //w1
  { day: 50, distance: 7, type: "runstrength" },
  { day: 51, distance: 8.4, type: "running", prevDistance: 7 },
  { day: 52, time: 40, type: "rythm" },
  { day: 53, distance: 6, type: "runstrength", prevDistance: 5 },
  { day: 54, type: "rest" },
  { day: 55, distance: 9.6, type: "running", prevDistance: 8 },
  { day: 56, distance: 19.2, type: "running", prevDistance: 16 },
  //w2
  { day: 57, type: "strength" },
  { day: 58, distance: 9.6, type: "running", prevDistance: 8 },
  {
    day: 59,
    distance: 6.48,
    type: "fartlek",
    fartlekReps: 9,
    prevDistance: 5.4,
  },
  { day: 60, distance: 6, type: "runstrength", prevDistance: 5 },
  {
    day: 61,
    distance: 3.5999999999999996,
    type: "running",
    prevDistance: 3,
  },
  { day: 62, type: "rest" },
  { day: 63, distance: 6, type: "running", prevDistance: 5 },
  //w3
  { day: 64, type: "strength" },
  { day: 65, distance: 9.6, type: "running", prevDistance: 8 },
  { day: 66, time: 45, type: "rythm" },
  { day: 67, distance: 6, type: "runstrength", prevDistance: 5 },
  { day: 68, type: "rest" },
  { day: 69, distance: 9.6, type: "running", prevDistance: 8 },
  {
    day: 70,
    distance: 21.599999999999998,
    type: "running",
    prevDistance: 18,
  },
  //w4
  { day: 71, type: "strength" },
  { day: 72, distance: 9.6, type: "running", prevDistance: 8 },
  {
    day: 73,
    distance: 7.199999999999999,
    type: "fartlek",
    fartlekReps: 10,
    prevDistance: 6,
  },
  { day: 74, distance: 6, type: "runstrength", prevDistance: 5 },
  { day: 75, type: "rest" },
  { day: 76, distance: 6, type: "running", prevDistance: 5 },
  { day: 77, distance: 22.8, type: "running", prevDistance: 19 },
  //w5
  { day: 78, type: "strength" },
  { day: 79, distance: 7.8, type: "running", prevDistance: 6.5 },
  { day: 80, time: 30, type: "rythm" },
  { day: 81, distance: 6, type: "runstrength", prevDistance: 5 },
  { day: 82, type: "rest" },
  { day: 83, type: "rest" },
  { day: 84, distance: 25.2, type: "running", prevDistance: 21 },
];
